export enum IntentCategory {
    HIGH_INTENT = 'HIGH_INTENT',
    BOUNCE_RISK = 'BOUNCE_RISK',
    HESITATION = 'HESITATION',
    RESEARCHER = 'RESEARCHER',
    GENERAL = 'GENERAL',
    PRICE_SENSITIVE = 'PRICE_SENSITIVE',
    FEATURE_EVALUATOR = 'FEATURE_EVALUATOR',
    CONFUSED = 'CONFUSED',
    RETURN_VISITOR = 'RETURN_VISITOR',
}
